name: starter
description: starter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <=3.4.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # State management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  bloc: ^8.1.2
  provider: ^6.0.5

  # Navigation
  go_router: ^14.1.4

  # Network
  dio: ^5.2.1+1

  # Storage
  flutter_secure_storage: ^9.2.2

  # Internationalization
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7

  # Utils
  url_launcher: ^6.1.7
  share_plus: ^7.2.1
  permission_handler: ^10.4.3
  rename: ^3.0.2

  # Other
  equatable: ^2.0.5
  collection: ^1.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Utils
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
