name: starter
description: starter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <=3.0.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # State management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  provider: ^6.0.5

  # Navigation
  go_router: ^9.0.3

  # Network
  dio: ^5.2.1+1

  # Internationalization
  intl: ^0.18.0

  # System
  notification_permissions: ^0.6.1
  flutter_local_notifications: ^15.1.0+1

  # Icons
  cupertino_icons: ^1.0.5

  # Other
  equatable: ^2.0.5
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Utils
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
